### ISSUE TITLE
mpe identifies the wrong pyton version

### ISSUE THREAD

**Issue by goern** [thoth-station/micropipenv#54] opened 2020-05-11 11:17 UTC
**Describe the bug**
micropipenv seems to identify the wrong python version:

```
...
---------------------------------- Pipfile.lock ----------------------------------
Running Python version 3.7, but Pipfile.lock requires Python version 3.6
$ python3 --version
Python 3.6.10
$ which python3
~/Work/thoth-station/user-api/venv/bin/python3
$ micropipenv --version 
0.1.5
```
**To Reproduce**
1. `virtualenv -p python3.6 -v ./venv `
2. `source ./venv/bin/activate`
3. `pip install micropipenv`
4. `git clone user-api && cd user-api`
5. `micropipenv install --deploy`

**Expected behavior**
it should be aware it is python3.6

**Comment by fridex** [comment] 2020-05-11 12:11
What are the outputs of:

`/usr/bin/env python3 --version` 

`which python3`

`python3 --version`

?

https://github.com/thoth-station/micropipenv/blob/0fd65f845a1fe18b494b9f266ee991016d7d7586/micropipenv.py#L1

**Comment by goern** [comment] 2020-05-11 15:57
it looks like some markers going crazy within an s2i-thoth build:

```
        "urllib3": {
            "hashes": [
                "sha256:a8a318824cc77d1fd4b2bec2ded92646630d7fe8619497b142c84a9e6f5a7293",
                "sha256:f3c5fd51747d450d4dcf6f923c81f78f811aab8205fda64b0aba34a4e48b0745"
            ],
            "index": "pypi-org",
            "markers": "(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((python_version >= \"3.4\") or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version >= \"3.4\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version != \"3.4\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version == \"2.7\")) or (python_version >= \"3.4\")) or (python_version == \"2.7\")",
            "version": "==1.25.7"
        },

```

**Comment by goern** [comment] 2020-05-11 15:58
> What are the outputs of:
> 
> `/usr/bin/env python3 --version`
> 
> `which python3`
> 
> `python3 --version`
> 
> ?
> 
> https://github.com/thoth-station/micropipenv/blob/0fd65f845a1fe18b494b9f266ee991016d7d7586/micropipenv.py#L1

It's `quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.12.3` that I'm using

**Comment by goern** [comment] 2020-05-11 16:10
https://github.com/thoth-station/s2i-thoth/issues/69

**Comment by goern** [comment] 2020-05-11 16:27
Not asking thoth services (advise or provenance) doesn't seem to screw up the Pipfile.lock

**Comment by fridex** [comment] 2020-05-18 06:32
This one is related to advises coming from Thoth where environment markers are probably not properly cloned when used in multiple scored stacks (memory optimization). I'll close this and create a relevant issue in adviser.

**Comment by fridex** [comment] 2020-05-18 06:32
Oh, reopening. The environment marker issue does not seem to be related to the original issue reported.

**Comment by fridex** [comment] 2020-05-18 11:06
> Steps to reproduce the behavior:
> 
> 1. `virtualenv -p python3.6 -v ./venv `
> 2. `source ./venv/bin/activate`
> 3. `pip install micropipenv`
> 4. `git clone user-api && cd user-api`
> 5. `micropipenv install --deploy`


I followed these steps using `quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.12.3`. The stack gets installed. Moreover Python 3.7 is not present in the container image at all so I'm curious from where Python 3.7 is detected.

Could it be that `quay.io/thoth-station/s2i-thoth-f31-py37:v0.12.3` was used? That carries Python 3.7 and this issue would correspond to the error reported as user-api requires Python 3.6 based on Pipfile.

**Comment by fridex** [comment] 2020-05-26 08:14
I'm closing this as I cannot reproduce the issue. Feel free to reopen if the issue persists.

**Closed by fridex** 2020-05-26 08:14 UTC
Labels: bug, human_intervention_required
