### ISSUE TITLE
Fail to export from poetry with no message

### ISSUE THREAD

**Issue by Alexander-Serov** [thoth-station/micropipenv#292] opened 2024-02-14 15:04 UTC
**Describe the bug**
Export fails with no error message.

**To Reproduce**
```
> micropipenv requirements --method poetry
'url'
> 
```
When trying to export requirements in my current project, I only get 'url' in return. No error message and no requirements file is produced.

**Expected behavior**
requirements.txt file is created or a clear error message is shown

**Screenshots**

**Additional context**
```
> micropipenv --version
1.6.0
```

**Comment by frenzymadness** [comment] 2024-02-14 22:50
Could you please provide pyproject.toml and poetry.lock or a link to your project so I can try to reproduce the problem you have?

**Comment by Alexander-Serov** [comment] 2024-02-15 13:00
> Could you please provide pyproject.toml and poetry.lock or a link to your project so I can try to reproduce the problem you have?

Hello, I am attaching the files here. I had to cut out and redact some of the private parts of it, but I hope you will be able to reproduce. Please let me know.

[Archive.zip](https://github.com/thoth-station/micropipenv/files/14297174/Archive.zip)

**Comment by frenzymadness** [comment] 2024-02-16 13:57
Thank you. I'm able to reproduce the problem and the truth is that the error message isn't very helpful so we have to do something with that.

The cause of the trouble is in this part:
```
[[tool.poetry.source]]
name = "source"
url = "***"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

Micropipenv expects every source to have an URL address, see:

https://github.com/thoth-station/micropipenv/blob/383bb66d770d0523d2249bb9e833ec1c5dae85c2/micropipenv.py#L762-L763

I'm not yet sure whether the poetry config is entirely valid without an url (and therefore the bug is in the false expectation of micropipenv) or not. In the meantime, you can fix the problem just by adding `url = "https://pypi.org/pypi/"` to the PyPI section.

**Comment by Alexander-Serov** [comment] 2024-02-16 15:47
Thanks @frenzymadness ,

Glad to hear there is an easy explanation to the observed behavior. Let me try and put the URL to see if the workaround works for me. A couple of comments in the meantime:
- the `tool.poetry.source` was created by poetry itself without a URL, so I would expect it to reproduce in other projects as well
- I agree, the question of whether the config is valid without a "URL" is interesting, even though poetry created it in my case
- A random search on Github has pointed me to this [23k-starrs Github repo](https://github.com/jumpserver/jumpserver/blob/58d30e7f85ad09711dc6cca0b5ed8b202f9a7929/pyproject.toml#L181) with the same problem, so I would expect 23k potential 👍 to this bug. 🐛
- Totally agree that printing a clearer message would have helped me debug the issue faster!

Thanks for having looked into it so fast!

**Comment by frenzymadness** [comment] 2024-07-29 10:50
I've prepared a PR to fix this issue. Sorry for the delay.

I've investigated your pyproject.toml and poetry.lock and found something interesting: It seems that it creates an endless loop when micropipenv processes the packages because it cannot decide the correct category for some of them. For example, package `awswrangler` is in the poetry.lock but it's neither a dependency of anything else nor directly mentioned in the pyproject.toml. Do you have an idea how this package ended up in poetry.lock?

**Comment by frenzymadness** [comment] 2024-07-30 11:53
> Would it make sense to check hashes of `poetry.lock` and `Pipfile.lock` files and eventually warn users if they do not match the expected value?

This sounds like a good idea if both hashes are calculated the same way.

The problem here is caused by the latest implementation change where if we cannot find the proper group for a package, we move it to the end of the queue. But if the package is not in pyproject.toml as a direct dependency and nothing depends on it in poetry.lock, it creates an endless loop. We can either try to check the hashes or implement another mechanism to avoid the endless loop.

I think we can create a new issue for that.

**Comment by frenzymadness** [comment] 2024-07-30 11:57
@fridex is this something you plan to work on now? If so, I can wait with the new release.

**Comment by Alexander-Serov** [comment] 2024-07-30 18:05
> Checking the archive, it looks like `poetry.lock` diverged from `pyproject.toml`:
> 
> ```
> $ cat poetry.lock
> ...
> content-hash = "ea90ae66786c34d6f7d365b95b456cb0c18f9683c76f6833f195076935b4dae5"
> $ sha256sum pyproject.toml 
> 5e71bfc9e57d479a600b9af18f7cefa33470114bebd2e1889371bed5eb192483  pyproject.toml
> ```
> 
> Would it make sense to check hashes of `poetry.lock` and `Pipfile.lock` files and eventually warn users if they do not match the expected value?

@fridex  Please keep in mind that I have redacted the pyproject.toml to keep out the private parts. Could it be the reason for the sha divergence?

**Comment by frenzymadness** [comment] 2024-07-31 06:46
I'm gonna close this issue and the main bug is resolved and open a new one for the endless loops. If you are interested in the hash checking, feel free to open it as an issue and we can work on that too.

**Closed by frenzymadness** 2024-07-31 06:46 UTC
